// words.js - 500 個台灣國小英文常見單字
// 10 等級，每級 50 個
// 舊 LV1→新 LV1(前50)+LV2(後50)，舊 LV2→LV3+LV4，以此類推

const WORDS = [

  // ==================== LEVEL 1（舊LV1前50）：顏色、數字、動物 ====================
  // 顏色 (10)
  { word: "red",      translation: "紅色",   emoji: "🔴", level: 1, category: "color" },
  { word: "blue",     translation: "藍色",   emoji: "🔵", level: 1, category: "color" },
  { word: "green",    translation: "綠色",   emoji: "💚", level: 1, category: "color" },
  { word: "yellow",   translation: "黃色",   emoji: "💛", level: 1, category: "color" },
  { word: "black",    translation: "黑色",   emoji: "⚫", level: 1, category: "color" },
  { word: "white",    translation: "白色",   emoji: "⚪", level: 1, category: "color" },
  { word: "pink",     translation: "粉紅色", emoji: "🩷", level: 1, category: "color" },
  { word: "orange",   translation: "橙色",   emoji: "🟠", level: 1, category: "color" },
  { word: "purple",   translation: "紫色",   emoji: "💜", level: 1, category: "color" },
  { word: "brown",    translation: "棕色",   emoji: "🟤", level: 1, category: "color" },
  // 數字 (10)
  { word: "one",      translation: "一", emoji: "1️⃣", level: 1, category: "number" },
  { word: "two",      translation: "二", emoji: "2️⃣", level: 1, category: "number" },
  { word: "three",    translation: "三", emoji: "3️⃣", level: 1, category: "number" },
  { word: "four",     translation: "四", emoji: "4️⃣", level: 1, category: "number" },
  { word: "five",     translation: "五", emoji: "5️⃣", level: 1, category: "number" },
  { word: "six",      translation: "六", emoji: "6️⃣", level: 1, category: "number" },
  { word: "seven",    translation: "七", emoji: "7️⃣", level: 1, category: "number" },
  { word: "eight",    translation: "八", emoji: "8️⃣", level: 1, category: "number" },
  { word: "nine",     translation: "九", emoji: "9️⃣", level: 1, category: "number" },
  { word: "ten",      translation: "十", emoji: "🔟", level: 1, category: "number" },
  // 動物 (30)
  { word: "cat",      translation: "貓",     emoji: "🐱", level: 1, category: "animal" },
  { word: "dog",      translation: "狗",     emoji: "🐶", level: 1, category: "animal" },
  { word: "bird",     translation: "鳥",     emoji: "🐦", level: 1, category: "animal" },
  { word: "fish",     translation: "魚",     emoji: "🐟", level: 1, category: "animal" },
  { word: "frog",     translation: "青蛙",   emoji: "🐸", level: 1, category: "animal" },
  { word: "rabbit",   translation: "兔子",   emoji: "🐰", level: 1, category: "animal" },
  { word: "bear",     translation: "熊",     emoji: "🐻", level: 1, category: "animal" },
  { word: "pig",      translation: "豬",     emoji: "🐷", level: 1, category: "animal" },
  { word: "cow",      translation: "牛",     emoji: "🐮", level: 1, category: "animal" },
  { word: "horse",    translation: "馬",     emoji: "🐴", level: 1, category: "animal" },
  { word: "duck",     translation: "鴨子",   emoji: "🦆", level: 1, category: "animal" },
  { word: "chicken",  translation: "雞",     emoji: "🐔", level: 1, category: "animal" },
  { word: "snake",    translation: "蛇",     emoji: "🐍", level: 1, category: "animal" },
  { word: "lion",     translation: "獅子",   emoji: "🦁", level: 1, category: "animal" },
  { word: "tiger",    translation: "老虎",   emoji: "🐯", level: 1, category: "animal" },
  { word: "elephant", translation: "大象",   emoji: "🐘", level: 1, category: "animal" },
  { word: "monkey",   translation: "猴子",   emoji: "🐵", level: 1, category: "animal" },
  { word: "panda",    translation: "熊貓",   emoji: "🐼", level: 1, category: "animal" },
  { word: "penguin",  translation: "企鵝",   emoji: "🐧", level: 1, category: "animal" },
  { word: "owl",      translation: "貓頭鷹", emoji: "🦉", level: 1, category: "animal" },
  { word: "fox",      translation: "狐狸",   emoji: "🦊", level: 1, category: "animal" },
  { word: "wolf",     translation: "狼",     emoji: "🐺", level: 1, category: "animal" },
  { word: "sheep",    translation: "羊",     emoji: "🐑", level: 1, category: "animal" },
  { word: "deer",     translation: "鹿",     emoji: "🦌", level: 1, category: "animal" },
  { word: "turtle",   translation: "烏龜",   emoji: "🐢", level: 1, category: "animal" },
  { word: "butterfly",translation: "蝴蝶",   emoji: "🦋", level: 1, category: "animal" },
  { word: "bee",      translation: "蜜蜂",   emoji: "🐝", level: 1, category: "animal" },
  { word: "ant",      translation: "螞蟻",   emoji: "🐜", level: 1, category: "animal" },
  { word: "crab",     translation: "螃蟹",   emoji: "🦀", level: 1, category: "animal" },
  { word: "whale",    translation: "鯨魚",   emoji: "🐳", level: 1, category: "animal" },

  // ==================== LEVEL 2（舊LV1後50）：水果、形狀、招呼語 ====================
  // 水果 (25)
  { word: "apple",      translation: "蘋果",   emoji: "🍎", level: 2, category: "fruit" },
  { word: "banana",     translation: "香蕉",   emoji: "🍌", level: 2, category: "fruit" },
  { word: "grape",      translation: "葡萄",   emoji: "🍇", level: 2, category: "fruit" },
  { word: "mango",      translation: "芒果",   emoji: "🥭", level: 2, category: "fruit" },
  { word: "peach",      translation: "桃子",   emoji: "🍑", level: 2, category: "fruit" },
  { word: "pear",       translation: "梨子",   emoji: "🍐", level: 2, category: "fruit" },
  { word: "lemon",      translation: "檸檬",   emoji: "🍋", level: 2, category: "fruit" },
  { word: "cherry",     translation: "櫻桃",   emoji: "🍒", level: 2, category: "fruit" },
  { word: "orange",     translation: "橘子",   emoji: "🍊", level: 2, category: "fruit" },
  { word: "watermelon", translation: "西瓜",   emoji: "🍉", level: 2, category: "fruit" },
  { word: "pineapple",  translation: "鳳梨",   emoji: "🍍", level: 2, category: "fruit" },
  { word: "strawberry", translation: "草莓",   emoji: "🍓", level: 2, category: "fruit" },
  { word: "blueberry",  translation: "藍莓",   emoji: "🫐", level: 2, category: "fruit" },
  { word: "kiwi",       translation: "奇異果", emoji: "🥝", level: 2, category: "fruit" },
  { word: "coconut",    translation: "椰子",   emoji: "🥥", level: 2, category: "fruit" },
  { word: "melon",      translation: "哈密瓜", emoji: "🍈", level: 2, category: "fruit" },
  { word: "plum",       translation: "李子",   emoji: null, level: 2, category: "fruit" },
  { word: "fig",        translation: "無花果", emoji: null, level: 2, category: "fruit" },
  { word: "papaya",     translation: "木瓜",   emoji: null, level: 2, category: "fruit" },
  { word: "guava",      translation: "芭樂",   emoji: null, level: 2, category: "fruit" },
  { word: "lychee",     translation: "荔枝",   emoji: null, level: 2, category: "fruit" },
  { word: "pomelo",     translation: "柚子",   emoji: null, level: 2, category: "fruit" },
  { word: "persimmon",  translation: "柿子",   emoji: null, level: 2, category: "fruit" },
  { word: "starfruit",  translation: "楊桃",   emoji: null, level: 2, category: "fruit" },
  { word: "longan",     translation: "龍眼",   emoji: null, level: 2, category: "fruit" },
  // 形狀 (10)
  { word: "circle",    translation: "圓形",   emoji: "⭕", level: 2, category: "shape" },
  { word: "square",    translation: "正方形", emoji: "🟥", level: 2, category: "shape" },
  { word: "triangle",  translation: "三角形", emoji: "🔺", level: 2, category: "shape" },
  { word: "star",      translation: "星形",   emoji: "⭐", level: 2, category: "shape" },
  { word: "heart",     translation: "心形",   emoji: "❤️", level: 2, category: "shape" },
  { word: "diamond",   translation: "菱形",   emoji: "💎", level: 2, category: "shape" },
  { word: "oval",      translation: "橢圓形", emoji: null, level: 2, category: "shape" },
  { word: "rectangle", translation: "長方形", emoji: null, level: 2, category: "shape" },
  { word: "cross",     translation: "十字形", emoji: "✝️", level: 2, category: "shape" },
  { word: "arrow",     translation: "箭頭形", emoji: "➡️", level: 2, category: "shape" },
  // 招呼語/基礎詞 (15)
  { word: "hello",   translation: "你好",   emoji: "👋", level: 2, category: "greeting" },
  { word: "bye",     translation: "再見",   emoji: null, level: 2, category: "greeting" },
  { word: "yes",     translation: "是",     emoji: "✅", level: 2, category: "greeting" },
  { word: "no",      translation: "否",     emoji: "❌", level: 2, category: "greeting" },
  { word: "please",  translation: "請",     emoji: "🙏", level: 2, category: "greeting" },
  { word: "thanks",  translation: "謝謝",   emoji: "😊", level: 2, category: "greeting" },
  { word: "sorry",   translation: "對不起", emoji: "😔", level: 2, category: "greeting" },
  { word: "good",    translation: "好",     emoji: "👍", level: 2, category: "greeting" },
  { word: "bad",     translation: "壞",     emoji: "👎", level: 2, category: "greeting" },
  { word: "big",     translation: "大",     emoji: "🐘", level: 2, category: "greeting" },
  { word: "small",   translation: "小",     emoji: "🐭", level: 2, category: "greeting" },
  { word: "hot",     translation: "熱",     emoji: "🔥", level: 2, category: "greeting" },
  { word: "cold",    translation: "冷",     emoji: "🧊", level: 2, category: "greeting" },
  { word: "happy",   translation: "快樂的", emoji: "😄", level: 2, category: "greeting" },
  { word: "sad",     translation: "難過的", emoji: "😢", level: 2, category: "greeting" },

  // ==================== LEVEL 3（舊LV2前50）：日常物品、食物前25 ====================
  // 日常物品 (25)
  { word: "book",     translation: "書",     emoji: "📚", level: 3, category: "object" },
  { word: "pen",      translation: "筆",     emoji: "✏️", level: 3, category: "object" },
  { word: "chair",    translation: "椅子",   emoji: null, level: 3, category: "object" },
  { word: "table",    translation: "桌子",   emoji: null, level: 3, category: "object" },
  { word: "phone",    translation: "電話",   emoji: "📱", level: 3, category: "object" },
  { word: "bag",      translation: "袋子",   emoji: "👜", level: 3, category: "object" },
  { word: "key",      translation: "鑰匙",   emoji: "🔑", level: 3, category: "object" },
  { word: "cup",      translation: "杯子",   emoji: "☕", level: 3, category: "object" },
  { word: "clock",    translation: "時鐘",   emoji: "🕐", level: 3, category: "object" },
  { word: "ball",     translation: "球",     emoji: "⚽", level: 3, category: "object" },
  { word: "box",      translation: "箱子",   emoji: "📦", level: 3, category: "object" },
  { word: "door",     translation: "門",     emoji: "🚪", level: 3, category: "object" },
  { word: "window",   translation: "窗戶",   emoji: null, level: 3, category: "object" },
  { word: "bed",      translation: "床",     emoji: "🛏️", level: 3, category: "object" },
  { word: "lamp",     translation: "燈",     emoji: "💡", level: 3, category: "object" },
  { word: "mirror",   translation: "鏡子",   emoji: null, level: 3, category: "object" },
  { word: "umbrella", translation: "雨傘",   emoji: "☂️", level: 3, category: "object" },
  { word: "scissors", translation: "剪刀",   emoji: "✂️", level: 3, category: "object" },
  { word: "ruler",    translation: "尺",     emoji: null, level: 3, category: "object" },
  { word: "eraser",   translation: "橡皮擦", emoji: null, level: 3, category: "object" },
  { word: "pencil",   translation: "鉛筆",   emoji: null, level: 3, category: "object" },
  { word: "notebook", translation: "筆記本", emoji: "📓", level: 3, category: "object" },
  { word: "map",      translation: "地圖",   emoji: "🗺️", level: 3, category: "object" },
  { word: "flag",     translation: "旗子",   emoji: "🚩", level: 3, category: "object" },
  { word: "basket",   translation: "籃子",   emoji: "🧺", level: 3, category: "object" },
  // 食物前 25
  { word: "bread",     translation: "麵包",   emoji: "🍞", level: 3, category: "food" },
  { word: "milk",      translation: "牛奶",   emoji: "🥛", level: 3, category: "food" },
  { word: "egg",       translation: "蛋",     emoji: "🥚", level: 3, category: "food" },
  { word: "rice",      translation: "米飯",   emoji: "🍚", level: 3, category: "food" },
  { word: "noodle",    translation: "麵條",   emoji: "🍜", level: 3, category: "food" },
  { word: "soup",      translation: "湯",     emoji: "🍲", level: 3, category: "food" },
  { word: "cake",      translation: "蛋糕",   emoji: "🎂", level: 3, category: "food" },
  { word: "cookie",    translation: "餅乾",   emoji: "🍪", level: 3, category: "food" },
  { word: "candy",     translation: "糖果",   emoji: "🍬", level: 3, category: "food" },
  { word: "ice cream", translation: "冰淇淋", emoji: "🍦", level: 3, category: "food" },
  { word: "pizza",     translation: "披薩",   emoji: "🍕", level: 3, category: "food" },
  { word: "burger",    translation: "漢堡",   emoji: "🍔", level: 3, category: "food" },
  { word: "hot dog",   translation: "熱狗",   emoji: "🌭", level: 3, category: "food" },
  { word: "salad",     translation: "沙拉",   emoji: "🥗", level: 3, category: "food" },
  { word: "sandwich",  translation: "三明治", emoji: "🥪", level: 3, category: "food" },
  { word: "cheese",    translation: "起司",   emoji: "🧀", level: 3, category: "food" },
  { word: "butter",    translation: "奶油",   emoji: null, level: 3, category: "food" },
  { word: "juice",     translation: "果汁",   emoji: "🧃", level: 3, category: "food" },
  { word: "water",     translation: "水",     emoji: "💧", level: 3, category: "food" },
  { word: "tea",       translation: "茶",     emoji: "🍵", level: 3, category: "food" },
  { word: "coffee",    translation: "咖啡",   emoji: null, level: 3, category: "food" },
  { word: "chocolate", translation: "巧克力", emoji: "🍫", level: 3, category: "food" },
  { word: "popcorn",   translation: "爆米花", emoji: "🍿", level: 3, category: "food" },
  { word: "sushi",     translation: "壽司",   emoji: "🍱", level: 3, category: "food" },
  { word: "dumpling",  translation: "餃子",   emoji: "🥟", level: 3, category: "food" },

  // ==================== LEVEL 4（舊LV2後50）：食物後5、身體、衣物 ====================
  // 食物後 5
  { word: "tofu",    translation: "豆腐",   emoji: null, level: 4, category: "food" },
  { word: "corn",    translation: "玉米",   emoji: "🌽", level: 4, category: "food" },
  { word: "carrot",  translation: "胡蘿蔔", emoji: "🥕", level: 4, category: "food" },
  { word: "potato",  translation: "馬鈴薯", emoji: "🥔", level: 4, category: "food" },
  { word: "onion",   translation: "洋蔥",   emoji: "🧅", level: 4, category: "food" },
  // 身體部位 (20)
  { word: "head",     translation: "頭",   emoji: null, level: 4, category: "body" },
  { word: "eye",      translation: "眼睛", emoji: "👁️", level: 4, category: "body" },
  { word: "ear",      translation: "耳朵", emoji: "👂", level: 4, category: "body" },
  { word: "nose",     translation: "鼻子", emoji: "👃", level: 4, category: "body" },
  { word: "mouth",    translation: "嘴巴", emoji: "👄", level: 4, category: "body" },
  { word: "hand",     translation: "手",   emoji: "✋", level: 4, category: "body" },
  { word: "foot",     translation: "腳",   emoji: "🦶", level: 4, category: "body" },
  { word: "arm",      translation: "手臂", emoji: "💪", level: 4, category: "body" },
  { word: "leg",      translation: "腿",   emoji: null, level: 4, category: "body" },
  { word: "hair",     translation: "頭髮", emoji: null, level: 4, category: "body" },
  { word: "face",     translation: "臉",   emoji: "😊", level: 4, category: "body" },
  { word: "neck",     translation: "脖子", emoji: null, level: 4, category: "body" },
  { word: "back",     translation: "背部", emoji: null, level: 4, category: "body" },
  { word: "chest",    translation: "胸部", emoji: null, level: 4, category: "body" },
  { word: "knee",     translation: "膝蓋", emoji: null, level: 4, category: "body" },
  { word: "elbow",    translation: "手肘", emoji: null, level: 4, category: "body" },
  { word: "finger",   translation: "手指", emoji: "☝️", level: 4, category: "body" },
  { word: "toe",      translation: "腳趾", emoji: null, level: 4, category: "body" },
  { word: "shoulder", translation: "肩膀", emoji: null, level: 4, category: "body" },
  { word: "stomach",  translation: "肚子", emoji: null, level: 4, category: "body" },
  // 衣物 (25)
  { word: "shirt",    translation: "上衣",   emoji: "👕", level: 4, category: "clothing" },
  { word: "pants",    translation: "褲子",   emoji: "👖", level: 4, category: "clothing" },
  { word: "dress",    translation: "洋裝",   emoji: "👗", level: 4, category: "clothing" },
  { word: "shoes",    translation: "鞋子",   emoji: "👟", level: 4, category: "clothing" },
  { word: "socks",    translation: "襪子",   emoji: "🧦", level: 4, category: "clothing" },
  { word: "hat",      translation: "帽子",   emoji: "🎩", level: 4, category: "clothing" },
  { word: "coat",     translation: "外套",   emoji: "🧥", level: 4, category: "clothing" },
  { word: "scarf",    translation: "圍巾",   emoji: "🧣", level: 4, category: "clothing" },
  { word: "gloves",   translation: "手套",   emoji: "🧤", level: 4, category: "clothing" },
  { word: "glasses",  translation: "眼鏡",   emoji: "👓", level: 4, category: "clothing" },
  { word: "belt",     translation: "皮帶",   emoji: null, level: 4, category: "clothing" },
  { word: "skirt",    translation: "裙子",   emoji: null, level: 4, category: "clothing" },
  { word: "jacket",   translation: "夾克",   emoji: null, level: 4, category: "clothing" },
  { word: "tie",      translation: "領帶",   emoji: "👔", level: 4, category: "clothing" },
  { word: "boots",    translation: "靴子",   emoji: "👢", level: 4, category: "clothing" },
  { word: "sandals",  translation: "涼鞋",   emoji: "👡", level: 4, category: "clothing" },
  { word: "sweater",  translation: "毛衣",   emoji: null, level: 4, category: "clothing" },
  { word: "uniform",  translation: "制服",   emoji: null, level: 4, category: "clothing" },
  { word: "pajamas",  translation: "睡衣",   emoji: null, level: 4, category: "clothing" },
  { word: "swimsuit", translation: "泳衣",   emoji: "👙", level: 4, category: "clothing" },
  { word: "raincoat", translation: "雨衣",   emoji: null, level: 4, category: "clothing" },
  { word: "apron",    translation: "圍裙",   emoji: null, level: 4, category: "clothing" },
  { word: "vest",     translation: "背心",   emoji: null, level: 4, category: "clothing" },
  { word: "cap",      translation: "鴨舌帽", emoji: "🧢", level: 4, category: "clothing" },
  { word: "backpack", translation: "背包",   emoji: "🎒", level: 4, category: "clothing" },

  // ==================== LEVEL 5（舊LV3前50）：學校、家庭、天氣前15 ====================
  // 學校用品 (20)
  { word: "classroom",  translation: "教室",   emoji: null,  level: 5, category: "school" },
  { word: "blackboard", translation: "黑板",   emoji: null,  level: 5, category: "school" },
  { word: "chalk",      translation: "粉筆",   emoji: null,  level: 5, category: "school" },
  { word: "library",    translation: "圖書館", emoji: "📖",  level: 5, category: "school" },
  { word: "computer",   translation: "電腦",   emoji: "💻",  level: 5, category: "school" },
  { word: "printer",    translation: "印表機", emoji: "🖨️", level: 5, category: "school" },
  { word: "crayon",     translation: "蠟筆",   emoji: "🖍️", level: 5, category: "school" },
  { word: "glue",       translation: "膠水",   emoji: null,  level: 5, category: "school" },
  { word: "tape",       translation: "膠帶",   emoji: null,  level: 5, category: "school" },
  { word: "pencil case",translation: "鉛筆盒", emoji: null,  level: 5, category: "school" },
  { word: "dictionary", translation: "字典",   emoji: null,  level: 5, category: "school" },
  { word: "globe",      translation: "地球儀", emoji: "🌐",  level: 5, category: "school" },
  { word: "calendar",   translation: "日曆",   emoji: "📅",  level: 5, category: "school" },
  { word: "folder",     translation: "資料夾", emoji: "📁",  level: 5, category: "school" },
  { word: "stapler",    translation: "訂書機", emoji: null,  level: 5, category: "school" },
  { word: "textbook",   translation: "課本",   emoji: null,  level: 5, category: "school" },
  { word: "homework",   translation: "作業",   emoji: null,  level: 5, category: "school" },
  { word: "test",       translation: "考試",   emoji: null,  level: 5, category: "school" },
  { word: "grade",      translation: "年級",   emoji: null,  level: 5, category: "school" },
  { word: "student",    translation: "學生",   emoji: "👨‍🎓", level: 5, category: "school" },
  // 家庭成員 (15)
  { word: "father",  translation: "父親",       emoji: "👨",    level: 5, category: "family" },
  { word: "mother",  translation: "母親",       emoji: "👩",    level: 5, category: "family" },
  { word: "brother", translation: "兄弟",       emoji: "👦",    level: 5, category: "family" },
  { word: "sister",  translation: "姐妹",       emoji: "👧",    level: 5, category: "family" },
  { word: "baby",    translation: "嬰兒",       emoji: "👶",    level: 5, category: "family" },
  { word: "grandpa", translation: "爺爺",       emoji: "👴",    level: 5, category: "family" },
  { word: "grandma", translation: "奶奶",       emoji: "👵",    level: 5, category: "family" },
  { word: "uncle",   translation: "叔叔",       emoji: null,    level: 5, category: "family" },
  { word: "aunt",    translation: "阿姨",       emoji: null,    level: 5, category: "family" },
  { word: "cousin",  translation: "表兄弟姐妹", emoji: null,    level: 5, category: "family" },
  { word: "family",  translation: "家人",       emoji: "👨‍👩‍👧‍👦", level: 5, category: "family" },
  { word: "friend",  translation: "朋友",       emoji: "🤝",    level: 5, category: "family" },
  { word: "teacher", translation: "老師",       emoji: "👨‍🏫", level: 5, category: "family" },
  { word: "doctor",  translation: "醫生",       emoji: "👨‍⚕️", level: 5, category: "family" },
  { word: "child",   translation: "孩子",       emoji: "🧒",    level: 5, category: "family" },
  // 天氣前 15
  { word: "sunny",   translation: "晴天的",   emoji: "☀️",  level: 5, category: "weather" },
  { word: "cloudy",  translation: "多雲的",   emoji: "☁️",  level: 5, category: "weather" },
  { word: "rainy",   translation: "下雨的",   emoji: "🌧️", level: 5, category: "weather" },
  { word: "snowy",   translation: "下雪的",   emoji: "❄️",  level: 5, category: "weather" },
  { word: "windy",   translation: "有風的",   emoji: "💨",  level: 5, category: "weather" },
  { word: "foggy",   translation: "有霧的",   emoji: "🌫️", level: 5, category: "weather" },
  { word: "stormy",  translation: "暴風雨的", emoji: "⛈️", level: 5, category: "weather" },
  { word: "thunder", translation: "雷",       emoji: "⚡",  level: 5, category: "weather" },
  { word: "rainbow", translation: "彩虹",     emoji: "🌈",  level: 5, category: "weather" },
  { word: "sunshine",translation: "陽光",     emoji: "🌞",  level: 5, category: "weather" },
  { word: "rain",    translation: "雨",       emoji: null, level: 5, category: "weather" },
  { word: "snow",    translation: "雪",       emoji: "🌨️", level: 5, category: "weather" },
  { word: "wind",    translation: "風",       emoji: null,  level: 5, category: "weather" },
  { word: "warm",    translation: "溫暖的",   emoji: null,  level: 5, category: "weather" },
  { word: "hot",     translation: "炎熱",     emoji: "🌡️", level: 5, category: "weather" },

  // ==================== LEVEL 6（舊LV3後50）：天氣後5、交通、地點 ====================
  // 天氣後 5
  { word: "cool",     translation: "涼爽的", emoji: "🍃",  level: 6, category: "weather" },
  { word: "freezing", translation: "冰凍的", emoji: "🧊",  level: 6, category: "weather" },
  { word: "humid",    translation: "潮濕的", emoji: null,  level: 6, category: "weather" },
  { word: "dry",      translation: "乾燥的", emoji: null,  level: 6, category: "weather" },
  { word: "typhoon",  translation: "颱風",   emoji: "🌀",  level: 6, category: "weather" },
  // 交通 (25)
  { word: "car",        translation: "汽車",   emoji: "🚗", level: 6, category: "transport" },
  { word: "bus",        translation: "公車",   emoji: "🚌", level: 6, category: "transport" },
  { word: "train",      translation: "火車",   emoji: "🚂", level: 6, category: "transport" },
  { word: "airplane",   translation: "飛機",   emoji: "✈️", level: 6, category: "transport" },
  { word: "boat",       translation: "船",     emoji: "⛵", level: 6, category: "transport" },
  { word: "bicycle",    translation: "腳踏車", emoji: "🚲", level: 6, category: "transport" },
  { word: "motorcycle", translation: "摩托車", emoji: "🏍️", level: 6, category: "transport" },
  { word: "truck",      translation: "卡車",   emoji: "🚚", level: 6, category: "transport" },
  { word: "taxi",       translation: "計程車", emoji: "🚕", level: 6, category: "transport" },
  { word: "subway",     translation: "地鐵",   emoji: "🚇", level: 6, category: "transport" },
  { word: "helicopter", translation: "直升機", emoji: "🚁", level: 6, category: "transport" },
  { word: "rocket",     translation: "火箭",   emoji: "🚀", level: 6, category: "transport" },
  { word: "ship",       translation: "大船",   emoji: "🚢", level: 6, category: "transport" },
  { word: "ambulance",  translation: "救護車", emoji: "🚑", level: 6, category: "transport" },
  { word: "police car", translation: "警車",   emoji: "🚓", level: 6, category: "transport" },
  { word: "fire truck", translation: "消防車", emoji: "🚒", level: 6, category: "transport" },
  { word: "scooter",    translation: "滑板車", emoji: "🛴", level: 6, category: "transport" },
  { word: "road",       translation: "道路",   emoji: "🛣️", level: 6, category: "transport" },
  { word: "bridge",     translation: "橋",     emoji: "🌉", level: 6, category: "transport" },
  { word: "station",    translation: "車站",   emoji: "🚉", level: 6, category: "transport" },
  { word: "airport",    translation: "機場",   emoji: "🛫", level: 6, category: "transport" },
  { word: "harbor",     translation: "港口",   emoji: null, level: 6, category: "transport" },
  { word: "tunnel",     translation: "隧道",   emoji: null, level: 6, category: "transport" },
  { word: "traffic",    translation: "交通",   emoji: "🚦", level: 6, category: "transport" },
  { word: "seat belt",  translation: "安全帶", emoji: null, level: 6, category: "transport" },
  // 地點 (20)
  { word: "bedroom",    translation: "臥室",   emoji: "🛏️", level: 6, category: "place" },
  { word: "kitchen",    translation: "廚房",   emoji: null,  level: 6, category: "place" },
  { word: "bathroom",   translation: "浴室",   emoji: "🛁",  level: 6, category: "place" },
  { word: "living room",translation: "客廳",   emoji: null,  level: 6, category: "place" },
  { word: "garden",     translation: "花園",   emoji: "🌻",  level: 6, category: "place" },
  { word: "park",       translation: "公園",   emoji: "🌳",  level: 6, category: "place" },
  { word: "school",     translation: "學校",   emoji: "🏫",  level: 6, category: "place" },
  { word: "hospital",   translation: "醫院",   emoji: "🏥",  level: 6, category: "place" },
  { word: "store",      translation: "商店",   emoji: "🏪",  level: 6, category: "place" },
  { word: "market",     translation: "市場",   emoji: "🛒",  level: 6, category: "place" },
  { word: "restaurant", translation: "餐廳",   emoji: "🍽️", level: 6, category: "place" },
  { word: "bank",       translation: "銀行",   emoji: "🏦",  level: 6, category: "place" },
  { word: "post office",translation: "郵局",   emoji: "📮",  level: 6, category: "place" },
  { word: "zoo",        translation: "動物園", emoji: "🦁",  level: 6, category: "place" },
  { word: "beach",      translation: "海灘",   emoji: "🏖️", level: 6, category: "place" },
  { word: "mountain",   translation: "山",     emoji: "⛰️", level: 6, category: "place" },
  { word: "forest",     translation: "森林",   emoji: "🌲",  level: 6, category: "place" },
  { word: "river",      translation: "河流",   emoji: "🏞️", level: 6, category: "place" },
  { word: "farm",       translation: "農場",   emoji: "🌾",  level: 6, category: "place" },
  { word: "church",     translation: "教堂",   emoji: "⛪",  level: 6, category: "place" },

  // ==================== LEVEL 7（舊LV4前50）：動作動詞、形容詞前15 ====================
  // 動作動詞 (35)
  { word: "run",     translation: "跑",     emoji: "🏃",    level: 7, category: "verb" },
  { word: "jump",    translation: "跳",     emoji: "🦘",    level: 7, category: "verb" },
  { word: "swim",    translation: "游泳",   emoji: "🏊",    level: 7, category: "verb" },
  { word: "fly",     translation: "飛",     emoji: "🦅",    level: 7, category: "verb" },
  { word: "eat",     translation: "吃",     emoji: "😋",    level: 7, category: "verb" },
  { word: "drink",   translation: "喝",     emoji: "🥤",    level: 7, category: "verb" },
  { word: "sleep",   translation: "睡覺",   emoji: "😴",    level: 7, category: "verb" },
  { word: "walk",    translation: "走路",   emoji: "🚶",    level: 7, category: "verb" },
  { word: "dance",   translation: "跳舞",   emoji: "💃",    level: 7, category: "verb" },
  { word: "sing",    translation: "唱歌",   emoji: "🎤",    level: 7, category: "verb" },
  { word: "read",    translation: "閱讀",   emoji: "📖",    level: 7, category: "verb" },
  { word: "write",   translation: "寫",     emoji: "✍️",   level: 7, category: "verb" },
  { word: "draw",    translation: "畫畫",   emoji: "🎨",    level: 7, category: "verb" },
  { word: "play",    translation: "玩",     emoji: "🎮",    level: 7, category: "verb" },
  { word: "cook",    translation: "烹飪",   emoji: "👨‍🍳", level: 7, category: "verb" },
  { word: "clean",   translation: "打掃",   emoji: "🧹",    level: 7, category: "verb" },
  { word: "drive",   translation: "駕駛",   emoji: "🚗",    level: 7, category: "verb" },
  { word: "climb",   translation: "爬",     emoji: "🧗",    level: 7, category: "verb" },
  { word: "kick",    translation: "踢",     emoji: "🦵",    level: 7, category: "verb" },
  { word: "throw",   translation: "丟",     emoji: "🤾",    level: 7, category: "verb" },
  { word: "catch",   translation: "接住",   emoji: null,    level: 7, category: "verb" },
  { word: "push",    translation: "推",     emoji: null,    level: 7, category: "verb" },
  { word: "pull",    translation: "拉",     emoji: null,    level: 7, category: "verb" },
  { word: "open",    translation: "打開",   emoji: "🔓",    level: 7, category: "verb" },
  { word: "close",   translation: "關閉",   emoji: "🔒",    level: 7, category: "verb" },
  { word: "buy",     translation: "買",     emoji: "🛍️",   level: 7, category: "verb" },
  { word: "sell",    translation: "賣",     emoji: null,    level: 7, category: "verb" },
  { word: "help",    translation: "幫助",   emoji: "🤝",    level: 7, category: "verb" },
  { word: "teach",   translation: "教導",   emoji: "👨‍🏫", level: 7, category: "verb" },
  { word: "learn",   translation: "學習",   emoji: "📚",    level: 7, category: "verb" },
  { word: "smile",   translation: "微笑",   emoji: "😊",    level: 7, category: "verb" },
  { word: "cry",     translation: "哭泣",   emoji: "😢",    level: 7, category: "verb" },
  { word: "laugh",   translation: "大笑",   emoji: "😂",    level: 7, category: "verb" },
  { word: "shout",   translation: "大喊",   emoji: "📢",    level: 7, category: "verb" },
  { word: "whisper", translation: "輕聲說", emoji: null,    level: 7, category: "verb" },
  // 形容詞前 15
  { word: "tall",    translation: "高的",   emoji: "🦒", level: 7, category: "adjective" },
  { word: "short",   translation: "矮的",   emoji: null, level: 7, category: "adjective" },
  { word: "long",    translation: "長的",   emoji: null, level: 7, category: "adjective" },
  { word: "wide",    translation: "寬的",   emoji: null, level: 7, category: "adjective" },
  { word: "narrow",  translation: "窄的",   emoji: null, level: 7, category: "adjective" },
  { word: "heavy",   translation: "重的",   emoji: "⚖️", level: 7, category: "adjective" },
  { word: "light",   translation: "輕的",   emoji: "🪶", level: 7, category: "adjective" },
  { word: "fast",    translation: "快的",   emoji: "⚡", level: 7, category: "adjective" },
  { word: "slow",    translation: "慢的",   emoji: "🐢", level: 7, category: "adjective" },
  { word: "strong",  translation: "強壯的", emoji: "💪", level: 7, category: "adjective" },
  { word: "weak",    translation: "虛弱的", emoji: null, level: 7, category: "adjective" },
  { word: "clean",   translation: "乾淨的", emoji: "✨", level: 7, category: "adjective" },
  { word: "dirty",   translation: "髒的",   emoji: null, level: 7, category: "adjective" },
  { word: "soft",    translation: "柔軟的", emoji: null, level: 7, category: "adjective" },
  { word: "hard",    translation: "堅硬的", emoji: "🪨", level: 7, category: "adjective" },

  // ==================== LEVEL 8（舊LV4後50）：形容詞後20、時間 ====================
  // 形容詞後 20
  { word: "sweet",   translation: "甜的",   emoji: "🍬", level: 8, category: "adjective" },
  { word: "sour",    translation: "酸的",   emoji: "🍋", level: 8, category: "adjective" },
  { word: "salty",   translation: "鹹的",   emoji: null, level: 8, category: "adjective" },
  { word: "spicy",   translation: "辣的",   emoji: "🌶️", level: 8, category: "adjective" },
  { word: "bitter",  translation: "苦的",   emoji: null, level: 8, category: "adjective" },
  { word: "bright",  translation: "明亮的", emoji: "💡", level: 8, category: "adjective" },
  { word: "dark",    translation: "黑暗的", emoji: "🌑", level: 8, category: "adjective" },
  { word: "loud",    translation: "吵的",   emoji: "📢", level: 8, category: "adjective" },
  { word: "quiet",   translation: "安靜的", emoji: "🤫", level: 8, category: "adjective" },
  { word: "young",   translation: "年輕的", emoji: "👶", level: 8, category: "adjective" },
  { word: "old",     translation: "年老的", emoji: "👴", level: 8, category: "adjective" },
  { word: "new",     translation: "新的",   emoji: "🆕", level: 8, category: "adjective" },
  { word: "full",    translation: "滿的",   emoji: null, level: 8, category: "adjective" },
  { word: "empty",   translation: "空的",   emoji: null, level: 8, category: "adjective" },
  { word: "round",   translation: "圓的",   emoji: "⭕", level: 8, category: "adjective" },
  { word: "flat",    translation: "平的",   emoji: null, level: 8, category: "adjective" },
  { word: "sharp",   translation: "尖銳的", emoji: "🗡️", level: 8, category: "adjective" },
  { word: "smooth",  translation: "光滑的", emoji: null, level: 8, category: "adjective" },
  { word: "rough",   translation: "粗糙的", emoji: null, level: 8, category: "adjective" },
  { word: "tired",   translation: "疲累的", emoji: "😴", level: 8, category: "adjective" },
  // 時間表達 (30)
  { word: "today",     translation: "今天",   emoji: "📅",  level: 8, category: "time" },
  { word: "tomorrow",  translation: "明天",   emoji: null,  level: 8, category: "time" },
  { word: "yesterday", translation: "昨天",   emoji: null,  level: 8, category: "time" },
  { word: "morning",   translation: "早上",   emoji: "🌅",  level: 8, category: "time" },
  { word: "afternoon", translation: "下午",   emoji: "🌤️", level: 8, category: "time" },
  { word: "evening",   translation: "傍晚",   emoji: "🌆",  level: 8, category: "time" },
  { word: "night",     translation: "夜晚",   emoji: "🌙",  level: 8, category: "time" },
  { word: "Monday",    translation: "星期一", emoji: null,  level: 8, category: "time" },
  { word: "Tuesday",   translation: "星期二", emoji: null,  level: 8, category: "time" },
  { word: "Wednesday", translation: "星期三", emoji: null,  level: 8, category: "time" },
  { word: "Thursday",  translation: "星期四", emoji: null,  level: 8, category: "time" },
  { word: "Friday",    translation: "星期五", emoji: "🎉",  level: 8, category: "time" },
  { word: "Saturday",  translation: "星期六", emoji: null,  level: 8, category: "time" },
  { word: "Sunday",    translation: "星期日", emoji: "☀️",  level: 8, category: "time" },
  { word: "January",   translation: "一月",   emoji: null,  level: 8, category: "time" },
  { word: "February",  translation: "二月",   emoji: null,  level: 8, category: "time" },
  { word: "March",     translation: "三月",   emoji: null,  level: 8, category: "time" },
  { word: "April",     translation: "四月",   emoji: null, level: 8, category: "time" },
  { word: "May",       translation: "五月",   emoji: null,  level: 8, category: "time" },
  { word: "June",      translation: "六月",   emoji: null,  level: 8, category: "time" },
  { word: "July",      translation: "七月",   emoji: null, level: 8, category: "time" },
  { word: "August",    translation: "八月",   emoji: null,  level: 8, category: "time" },
  { word: "September", translation: "九月",   emoji: null,  level: 8, category: "time" },
  { word: "October",   translation: "十月",   emoji: null,  level: 8, category: "time" },
  { word: "November",  translation: "十一月", emoji: null,  level: 8, category: "time" },
  { word: "December",  translation: "十二月", emoji: null,  level: 8, category: "time" },
  { word: "stand up",  translation: "起立",   emoji: "⬆️", level: 9, category: "phrase" },
  { word: "sit down",  translation: "坐下",   emoji: "⬇️", level: 9, category: "phrase" },
  { word: "line up",   translation: "排隊",   emoji: null, level: 9, category: "phrase" },
  { word: "hurry up",  translation: "快點",   emoji: "⏩", level: 9, category: "phrase" },

  // ==================== LEVEL 9（舊LV5前50）：複雜名詞、複合表達 ====================
  // 複雜名詞 (25)
  { word: "adventure",   translation: "冒險",   emoji: "⚔️",  level: 9, category: "noun" },
  { word: "treasure",    translation: "寶藏",   emoji: "💰",  level: 9, category: "noun" },
  { word: "mystery",     translation: "謎",     emoji: "🔍",  level: 9, category: "noun" },
  { word: "courage",     translation: "勇氣",   emoji: "💪",  level: 9, category: "noun" },
  { word: "knowledge",   translation: "知識",   emoji: "🧠",  level: 9, category: "noun" },
  { word: "science",     translation: "科學",   emoji: "🔬",  level: 9, category: "noun" },
  { word: "history",     translation: "歷史",   emoji: "📜",  level: 9, category: "noun" },
  { word: "culture",     translation: "文化",   emoji: null,  level: 9, category: "noun" },
  { word: "nature",      translation: "自然",   emoji: "🌿",  level: 9, category: "noun" },
  { word: "energy",      translation: "能量",   emoji: "⚡",  level: 9, category: "noun" },
  { word: "freedom",     translation: "自由",   emoji: "🕊️", level: 9, category: "noun" },
  { word: "peace",       translation: "和平",   emoji: "☮️",  level: 9, category: "noun" },
  { word: "justice",     translation: "正義",   emoji: "⚖️",  level: 9, category: "noun" },
  { word: "environment", translation: "環境",   emoji: "🌍",  level: 9, category: "noun" },
  { word: "technology",  translation: "科技",   emoji: "💻",  level: 9, category: "noun" },
  { word: "invention",   translation: "發明",   emoji: "💡",  level: 9, category: "noun" },
  { word: "planet",      translation: "行星",   emoji: "🪐",  level: 9, category: "noun" },
  { word: "universe",    translation: "宇宙",   emoji: null,  level: 9, category: "noun" },
  { word: "ocean",       translation: "海洋",   emoji: "🌊",  level: 9, category: "noun" },
  { word: "volcano",     translation: "火山",   emoji: "🌋",  level: 9, category: "noun" },
  { word: "earthquake",  translation: "地震",   emoji: null,  level: 9, category: "noun" },
  { word: "tornado",     translation: "龍捲風", emoji: "🌪️", level: 9, category: "noun" },
  { word: "desert",      translation: "沙漠",   emoji: "🏜️", level: 9, category: "noun" },
  { word: "jungle",      translation: "叢林",   emoji: "🌴",  level: 9, category: "noun" },
  { word: "continent",   translation: "大陸",   emoji: null,  level: 9, category: "noun" },
  // 複合表達 (25)
  { word: "go to school", translation: "去上學",     emoji: null, level: 9, category: "phrase" },
  { word: "wake up",      translation: "起床",       emoji: "⏰", level: 9, category: "phrase" },
  { word: "brush teeth",  translation: "刷牙",       emoji: "🦷", level: 9, category: "phrase" },
  { word: "take a bath",  translation: "洗澡",       emoji: "🛁", level: 9, category: "phrase" },
  { word: "do homework",  translation: "做功課",     emoji: "📝", level: 9, category: "phrase" },
  { word: "go to bed",    translation: "去睡覺",     emoji: "😴", level: 9, category: "phrase" },
  { word: "have lunch",   translation: "吃午餐",     emoji: "🍱", level: 9, category: "phrase" },
  { word: "take a photo", translation: "拍照",       emoji: "📷", level: 9, category: "phrase" },
  { word: "turn off",     translation: "關掉",       emoji: "🔴", level: 9, category: "phrase" },
  { word: "turn on",      translation: "打開(開啟)", emoji: "🟢", level: 9, category: "phrase" },
  { word: "look for",     translation: "尋找",       emoji: null, level: 9, category: "phrase" },
  { word: "take care",    translation: "照顧",       emoji: null, level: 9, category: "phrase" },
  { word: "give up",      translation: "放棄",       emoji: null, level: 9, category: "phrase" },
  { word: "try again",    translation: "再試一次",   emoji: "🔄", level: 9, category: "phrase" },
  { word: "well done",    translation: "做得好",     emoji: "👏", level: 9, category: "phrase" },
  { word: "be careful",   translation: "小心",       emoji: "⚠️", level: 9, category: "phrase" },
  { word: "come in",      translation: "進來",       emoji: null, level: 9, category: "phrase" },
  { word: "go out",       translation: "出去",       emoji: null, level: 9, category: "phrase" },
  { word: "spring",    translation: "春天",   emoji: "🌸",  level: 8, category: "time" },
  { word: "summer",    translation: "夏天",   emoji: null,  level: 8, category: "time" },
  { word: "autumn",    translation: "秋天",   emoji: "🍂",  level: 8, category: "time" },
  { word: "winter",    translation: "冬天",   emoji: "❄️",  level: 8, category: "time" },
  { word: "calm down",    translation: "冷靜",       emoji: null, level: 9, category: "phrase" },
  { word: "speak up",     translation: "大聲說",     emoji: "🔊", level: 9, category: "phrase" },
  { word: "listen to",    translation: "聆聽",       emoji: "👂", level: 9, category: "phrase" },

  // ==================== LEVEL 10（舊LV5後50）：學術用語、進階形容詞 ====================
  // 學術用語 (25)
  { word: "addition",     translation: "加法",     emoji: "➕",  level: 10, category: "academic" },
  { word: "subtraction",  translation: "減法",     emoji: "➖",  level: 10, category: "academic" },
  { word: "multiply",     translation: "乘法",     emoji: "✖️",  level: 10, category: "academic" },
  { word: "divide",       translation: "除法",     emoji: "➗",  level: 10, category: "academic" },
  { word: "equal",        translation: "相等",     emoji: "🟰",  level: 10, category: "academic" },
  { word: "grammar",      translation: "文法",     emoji: null,  level: 10, category: "academic" },
  { word: "vocabulary",   translation: "字彙",     emoji: null,  level: 10, category: "academic" },
  { word: "sentence",     translation: "句子",     emoji: null,  level: 10, category: "academic" },
  { word: "paragraph",    translation: "段落",     emoji: null,  level: 10, category: "academic" },
  { word: "chapter",      translation: "章節",     emoji: "📖",  level: 10, category: "academic" },
  { word: "experiment",   translation: "實驗",     emoji: "🧪",  level: 10, category: "academic" },
  { word: "conclusion",   translation: "結論",     emoji: null,  level: 10, category: "academic" },
  { word: "research",     translation: "研究",     emoji: "🔬",  level: 10, category: "academic" },
  { word: "project",      translation: "作業計畫", emoji: null,  level: 10, category: "academic" },
  { word: "presentation", translation: "報告",     emoji: "📊",  level: 10, category: "academic" },
  { word: "interview",    translation: "面談",     emoji: null, level: 10, category: "academic" },
  { word: "examination",  translation: "考試",     emoji: "📋",  level: 10, category: "academic" },
  { word: "certificate",  translation: "證書",     emoji: null,  level: 10, category: "academic" },
  { word: "scholarship",  translation: "獎學金",   emoji: null,  level: 10, category: "academic" },
  { word: "education",    translation: "教育",     emoji: "🎓",  level: 10, category: "academic" },
  { word: "population",   translation: "人口",     emoji: null,  level: 10, category: "academic" },
  { word: "electricity",  translation: "電力",     emoji: "⚡",  level: 10, category: "academic" },
  { word: "gravity",      translation: "重力",     emoji: null,  level: 10, category: "academic" },
  { word: "temperature",  translation: "溫度",     emoji: "🌡️", level: 10, category: "academic" },
  { word: "pollution",    translation: "污染",     emoji: "🏭",  level: 10, category: "academic" },
  // 進階形容詞 (25)
  { word: "excellent",    translation: "優秀的",   emoji: null, level: 10, category: "adv_adj" },
  { word: "wonderful",    translation: "美妙的",   emoji: null, level: 10, category: "adv_adj" },
  { word: "terrible",     translation: "可怕的",   emoji: "😱", level: 10, category: "adv_adj" },
  { word: "fantastic",    translation: "太棒了",   emoji: "🎉", level: 10, category: "adv_adj" },
  { word: "amazing",      translation: "驚人的",   emoji: "😲", level: 10, category: "adv_adj" },
  { word: "boring",       translation: "無聊的",   emoji: "😑", level: 10, category: "adv_adj" },
  { word: "interesting",  translation: "有趣的",   emoji: "🤔", level: 10, category: "adv_adj" },
  { word: "difficult",    translation: "困難的",   emoji: "😓", level: 10, category: "adv_adj" },
  { word: "easy",         translation: "容易的",   emoji: "😊", level: 10, category: "adv_adj" },
  { word: "important",    translation: "重要的",   emoji: "❗", level: 10, category: "adv_adj" },
  { word: "famous",       translation: "著名的",   emoji: null, level: 10, category: "adv_adj" },
  { word: "special",      translation: "特別的",   emoji: null, level: 10, category: "adv_adj" },
  { word: "dangerous",    translation: "危險的",   emoji: "⚠️", level: 10, category: "adv_adj" },
  { word: "healthy",      translation: "健康的",   emoji: null, level: 10, category: "adv_adj" },
  { word: "beautiful",    translation: "美麗的",   emoji: "🌸", level: 10, category: "adv_adj" },
  { word: "ugly",         translation: "醜陋的",   emoji: null, level: 10, category: "adv_adj" },
  { word: "comfortable",  translation: "舒適的",   emoji: "😌", level: 10, category: "adv_adj" },
  { word: "nervous",      translation: "緊張的",   emoji: "😰", level: 10, category: "adv_adj" },
  { word: "excited",      translation: "興奮的",   emoji: "🤩", level: 10, category: "adv_adj" },
  { word: "bored",        translation: "感到無聊", emoji: "🥱", level: 10, category: "adv_adj" },
  { word: "surprised",    translation: "驚訝的",   emoji: "😮", level: 10, category: "adv_adj" },
  { word: "confused",     translation: "困惑的",   emoji: "😕", level: 10, category: "adv_adj" },
  { word: "proud",        translation: "驕傲的",   emoji: "😤", level: 10, category: "adv_adj" },
  { word: "lonely",       translation: "孤獨的",   emoji: "😞", level: 10, category: "adv_adj" },
  { word: "grateful",     translation: "感激的",   emoji: "🙏", level: 10, category: "adv_adj" },
];
