// words_vol2.js - 500 個台灣國小英文常見單字（第二冊）
// 10 等級，每級 50 個
// 與 words.js 無重複，主題更豐富

const WORDS_VOL2 = [

  // ==================== LEVEL 1：更多動物 (30) + 昆蟲 (20) ====================
  // 更多動物 (30)
  { word: "peacock",     translation: "孔雀",     emoji: "🦚", level: 1, category: "animal" },
  { word: "flamingo",    translation: "紅鶴",     emoji: "🦩", level: 1, category: "animal" },
  { word: "zebra",       translation: "斑馬",     emoji: "🦓", level: 1, category: "animal" },
  { word: "giraffe",     translation: "長頸鹿",   emoji: "🦒", level: 1, category: "animal" },
  { word: "hippo",       translation: "河馬",     emoji: "🦛", level: 1, category: "animal" },
  { word: "gorilla",     translation: "大猩猩",   emoji: "🦍", level: 1, category: "animal" },
  { word: "koala",       translation: "無尾熊",   emoji: "🐨", level: 1, category: "animal" },
  { word: "kangaroo",    translation: "袋鼠",     emoji: "🦘", level: 1, category: "animal" },
  { word: "squirrel",    translation: "松鼠",     emoji: "🐿️", level: 1, category: "animal" },
  { word: "hedgehog",    translation: "刺蝟",     emoji: "🦔", level: 1, category: "animal" },
  { word: "raccoon",     translation: "浣熊",     emoji: "🦝", level: 1, category: "animal" },
  { word: "parrot",      translation: "鸚鵡",     emoji: "🦜", level: 1, category: "animal" },
  { word: "swan",        translation: "天鵝",     emoji: "🦢", level: 1, category: "animal" },
  { word: "eagle",       translation: "老鷹",     emoji: "🦅", level: 1, category: "animal" },
  { word: "bat",         translation: "蝙蝠",     emoji: "🦇", level: 1, category: "animal" },
  { word: "crocodile",   translation: "鱷魚",     emoji: "🐊", level: 1, category: "animal" },
  { word: "rhino",       translation: "犀牛",     emoji: "🦏", level: 1, category: "animal" },
  { word: "cheetah",     translation: "獵豹",     emoji: "🐆", level: 1, category: "animal" },
  { word: "leopard",     translation: "花豹",     emoji: "🐆", level: 1, category: "animal" },
  { word: "camel",       translation: "駱駝",     emoji: "🐪", level: 1, category: "animal" },
  { word: "llama",       translation: "羊駝",     emoji: "🦙", level: 1, category: "animal" },
  { word: "moose",       translation: "麋鹿",     emoji: "🫎", level: 1, category: "animal" },
  { word: "bison",       translation: "野牛",     emoji: "🦬", level: 1, category: "animal" },
  { word: "otter",       translation: "水獺",     emoji: "🦦", level: 1, category: "animal" },
  { word: "skunk",       translation: "臭鼬",     emoji: "🦨", level: 1, category: "animal" },
  { word: "beaver",      translation: "海狸",     emoji: "🦫", level: 1, category: "animal" },
  { word: "polar bear",  translation: "北極熊",   emoji: "🐻‍❄️", level: 1, category: "animal" },
  { word: "hummingbird", translation: "蜂鳥",     emoji: "🐦", level: 1, category: "animal" },
  { word: "pelican",     translation: "鵜鶘",     emoji: "🐦", level: 1, category: "animal" },
  { word: "stork",       translation: "鸛鳥",     emoji: "🐦", level: 1, category: "animal" },
  // 昆蟲 (20)
  { word: "ladybug",     translation: "瓢蟲",     emoji: "🐞", level: 1, category: "insect" },
  { word: "grasshopper", translation: "蚱蜢",     emoji: "🦗", level: 1, category: "insect" },
  { word: "dragonfly",   translation: "蜻蜓",     emoji: null, level: 1, category: "insect" },
  { word: "caterpillar", translation: "毛毛蟲",   emoji: "🐛", level: 1, category: "insect" },
  { word: "worm",        translation: "蚯蚓",     emoji: "🪱", level: 1, category: "insect" },
  { word: "snail",       translation: "蝸牛",     emoji: "🐌", level: 1, category: "insect" },
  { word: "beetle",      translation: "甲蟲",     emoji: "🪲", level: 1, category: "insect" },
  { word: "firefly",     translation: "螢火蟲",   emoji: "✨", level: 1, category: "insect" },
  { word: "mosquito",    translation: "蚊子",     emoji: "🦟", level: 1, category: "insect" },
  { word: "cricket",     translation: "蟋蟀",     emoji: "🦗", level: 1, category: "insect" },
  { word: "wasp",        translation: "黃蜂",     emoji: "🐝", level: 1, category: "insect" },
  { word: "moth",        translation: "蛾",       emoji: null, level: 1, category: "insect" },
  { word: "slug",        translation: "蛞蝓",     emoji: null, level: 1, category: "insect" },
  { word: "centipede",   translation: "蜈蚣",     emoji: null, level: 1, category: "insect" },
  { word: "spider",      translation: "蜘蛛",     emoji: "🕷️", level: 1, category: "insect" },
  { word: "scorpion",    translation: "蠍子",     emoji: "🦂", level: 1, category: "insect" },
  { word: "mantis",      translation: "螳螂",     emoji: null, level: 1, category: "insect" },
  { word: "flea",        translation: "跳蚤",     emoji: null, level: 1, category: "insect" },
  { word: "termite",     translation: "白蟻",     emoji: null, level: 1, category: "insect" },
  { word: "cockroach",   translation: "蟑螂",     emoji: "🪳", level: 1, category: "insect" },

  // ==================== LEVEL 2：蔬菜 (25) + 飲料 (25) ====================
  // 蔬菜 (25)
  { word: "broccoli",    translation: "花椰菜",   emoji: "🥦", level: 2, category: "vegetable" },
  { word: "spinach",     translation: "菠菜",     emoji: "🥬", level: 2, category: "vegetable" },
  { word: "cabbage",     translation: "高麗菜",   emoji: "🥬", level: 2, category: "vegetable" },
  { word: "garlic",      translation: "大蒜",     emoji: "🧄", level: 2, category: "vegetable" },
  { word: "tomato",      translation: "番茄",     emoji: "🍅", level: 2, category: "vegetable" },
  { word: "cucumber",    translation: "黃瓜",     emoji: "🥒", level: 2, category: "vegetable" },
  { word: "pepper",      translation: "辣椒",     emoji: "🌶️", level: 2, category: "vegetable" },
  { word: "eggplant",    translation: "茄子",     emoji: "🍆", level: 2, category: "vegetable" },
  { word: "lettuce",     translation: "萵苣",     emoji: "🥬", level: 2, category: "vegetable" },
  { word: "celery",      translation: "芹菜",     emoji: null, level: 2, category: "vegetable" },
  { word: "mushroom",    translation: "蘑菇",     emoji: "🍄", level: 2, category: "vegetable" },
  { word: "pumpkin",     translation: "南瓜",     emoji: "🎃", level: 2, category: "vegetable" },
  { word: "radish",      translation: "蘿蔔",     emoji: null, level: 2, category: "vegetable" },
  { word: "bean",        translation: "豆子",     emoji: null, level: 2, category: "vegetable" },
  { word: "pea",         translation: "豌豆",     emoji: null, level: 2, category: "vegetable" },
  { word: "leek",        translation: "韭蔥",     emoji: null, level: 2, category: "vegetable" },
  { word: "ginger",      translation: "薑",       emoji: null, level: 2, category: "vegetable" },
  { word: "asparagus",   translation: "蘆筍",     emoji: null, level: 2, category: "vegetable" },
  { word: "cauliflower", translation: "白花椰菜", emoji: null, level: 2, category: "vegetable" },
  { word: "zucchini",    translation: "義大利瓜", emoji: null, level: 2, category: "vegetable" },
  { word: "beet",        translation: "甜菜",     emoji: null, level: 2, category: "vegetable" },
  { word: "sweet potato",translation: "地瓜",     emoji: "🍠", level: 2, category: "vegetable" },
  { word: "taro",        translation: "芋頭",     emoji: null, level: 2, category: "vegetable" },
  { word: "bamboo shoot",translation: "竹筍",     emoji: null, level: 2, category: "vegetable" },
  { word: "okra",        translation: "秋葵",     emoji: null, level: 2, category: "vegetable" },
  // 飲料 (25)
  { word: "soda",        translation: "汽水",     emoji: "🥤", level: 2, category: "drink" },
  { word: "lemonade",    translation: "檸檬水",   emoji: "🍋", level: 2, category: "drink" },
  { word: "smoothie",    translation: "果昔",     emoji: "🥤", level: 2, category: "drink" },
  { word: "cocoa",       translation: "可可",     emoji: "🍫", level: 2, category: "drink" },
  { word: "yogurt",      translation: "優格",     emoji: "🥛", level: 2, category: "drink" },
  { word: "cola",        translation: "可樂",     emoji: "🥤", level: 2, category: "drink" },
  { word: "hot chocolate",translation: "熱巧克力",emoji: "☕", level: 2, category: "drink" },
  { word: "bubble tea",  translation: "珍珠奶茶", emoji: "🧋", level: 2, category: "drink" },
  { word: "orange juice",translation: "柳橙汁",   emoji: "🍊", level: 2, category: "drink" },
  { word: "apple juice", translation: "蘋果汁",   emoji: "🍎", level: 2, category: "drink" },
  { word: "grape juice", translation: "葡萄汁",   emoji: "🍇", level: 2, category: "drink" },
  { word: "milkshake",   translation: "奶昔",     emoji: "🥛", level: 2, category: "drink" },
  { word: "syrup",       translation: "糖漿",     emoji: null, level: 2, category: "drink" },
  { word: "vinegar",     translation: "醋",       emoji: null, level: 2, category: "drink" },
  { word: "sauce",       translation: "醬料",     emoji: null, level: 2, category: "drink" },
  { word: "broth",       translation: "高湯",     emoji: "🍲", level: 2, category: "drink" },
  { word: "cream",       translation: "鮮奶油",   emoji: null, level: 2, category: "drink" },
  { word: "mineral water",translation: "礦泉水",  emoji: "💧", level: 2, category: "drink" },
  { word: "green tea",   translation: "綠茶",     emoji: "🍵", level: 2, category: "drink" },
  { word: "black tea",   translation: "紅茶",     emoji: "🍵", level: 2, category: "drink" },
  { word: "sports drink",translation: "運動飲料", emoji: "🥤", level: 2, category: "drink" },
  { word: "energy drink",translation: "能量飲料", emoji: "🥤", level: 2, category: "drink" },
  { word: "herbal tea",  translation: "花草茶",   emoji: "🍵", level: 2, category: "drink" },
  { word: "tomato juice",translation: "番茄汁",   emoji: "🍅", level: 2, category: "drink" },
  { word: "coconut milk",translation: "椰奶",     emoji: "🥥", level: 2, category: "drink" },

  // ==================== LEVEL 3：運動 (25) + 嗜好 (25) ====================
  // 運動 (25)
  { word: "soccer",      translation: "足球",     emoji: "⚽", level: 3, category: "sport" },
  { word: "basketball",  translation: "籃球",     emoji: "🏀", level: 3, category: "sport" },
  { word: "baseball",    translation: "棒球",     emoji: "⚾", level: 3, category: "sport" },
  { word: "tennis",      translation: "網球",     emoji: "🎾", level: 3, category: "sport" },
  { word: "swimming",    translation: "游泳",     emoji: "🏊", level: 3, category: "sport" },
  { word: "running",     translation: "跑步",     emoji: "🏃", level: 3, category: "sport" },
  { word: "cycling",     translation: "騎自行車", emoji: "🚴", level: 3, category: "sport" },
  { word: "skating",     translation: "溜冰",     emoji: "⛸️", level: 3, category: "sport" },
  { word: "skiing",      translation: "滑雪",     emoji: "⛷️", level: 3, category: "sport" },
  { word: "gymnastics",  translation: "體操",     emoji: "🤸", level: 3, category: "sport" },
  { word: "volleyball",  translation: "排球",     emoji: "🏐", level: 3, category: "sport" },
  { word: "badminton",   translation: "羽毛球",   emoji: "🏸", level: 3, category: "sport" },
  { word: "boxing",      translation: "拳擊",     emoji: "🥊", level: 3, category: "sport" },
  { word: "wrestling",   translation: "摔角",     emoji: "🤼", level: 3, category: "sport" },
  { word: "archery",     translation: "射箭",     emoji: "🏹", level: 3, category: "sport" },
  { word: "golf",        translation: "高爾夫",   emoji: "⛳", level: 3, category: "sport" },
  { word: "surfing",     translation: "衝浪",     emoji: "🏄", level: 3, category: "sport" },
  { word: "diving",      translation: "潛水",     emoji: "🤿", level: 3, category: "sport" },
  { word: "hiking",      translation: "健行",     emoji: "🥾", level: 3, category: "sport" },
  { word: "yoga",        translation: "瑜珈",     emoji: "🧘", level: 3, category: "sport" },
  { word: "table tennis",translation: "桌球",     emoji: "🏓", level: 3, category: "sport" },
  { word: "bowling",     translation: "保齡球",   emoji: "🎳", level: 3, category: "sport" },
  { word: "taekwondo",   translation: "跆拳道",   emoji: "🥋", level: 3, category: "sport" },
  { word: "track",       translation: "田徑",     emoji: "🏅", level: 3, category: "sport" },
  { word: "skateboard",  translation: "滑板",     emoji: "🛹", level: 3, category: "sport" },
  // 嗜好 (25)
  { word: "painting",    translation: "畫畫",     emoji: "🎨", level: 3, category: "hobby" },
  { word: "drawing",     translation: "素描",     emoji: "✏️", level: 3, category: "hobby" },
  { word: "reading",     translation: "閱讀",     emoji: "📚", level: 3, category: "hobby" },
  { word: "singing",     translation: "唱歌",     emoji: "🎤", level: 3, category: "hobby" },
  { word: "cooking",     translation: "烹飪",     emoji: "🍳", level: 3, category: "hobby" },
  { word: "gardening",   translation: "園藝",     emoji: "🌱", level: 3, category: "hobby" },
  { word: "photography", translation: "攝影",     emoji: "📷", level: 3, category: "hobby" },
  { word: "collecting",  translation: "收集",     emoji: "🗃️", level: 3, category: "hobby" },
  { word: "knitting",    translation: "編織",     emoji: "🧶", level: 3, category: "hobby" },
  { word: "fishing",     translation: "釣魚",     emoji: "🎣", level: 3, category: "hobby" },
  { word: "camping",     translation: "露營",     emoji: "🏕️", level: 3, category: "hobby" },
  { word: "puzzle",      translation: "拼圖",     emoji: "🧩", level: 3, category: "hobby" },
  { word: "writing",     translation: "寫作",     emoji: "📝", level: 3, category: "hobby" },
  { word: "sculpting",   translation: "雕刻",     emoji: "🗿", level: 3, category: "hobby" },
  { word: "music",       translation: "音樂",     emoji: "🎵", level: 3, category: "hobby" },
  { word: "chess",       translation: "西洋棋",   emoji: "♟️", level: 3, category: "hobby" },
  { word: "dancing",     translation: "舞蹈",     emoji: "💃", level: 3, category: "hobby" },
  { word: "magic",       translation: "魔術",     emoji: "🪄", level: 3, category: "hobby" },
  { word: "origami",     translation: "折紙",     emoji: "📄", level: 3, category: "hobby" },
  { word: "baking",      translation: "烘焙",     emoji: "🥐", level: 3, category: "hobby" },
  { word: "traveling",   translation: "旅行",     emoji: "✈️", level: 3, category: "hobby" },
  { word: "gaming",      translation: "玩遊戲",   emoji: "🎮", level: 3, category: "hobby" },
  { word: "calligraphy", translation: "書法",     emoji: "🖌️", level: 3, category: "hobby" },
  { word: "sewing",      translation: "縫紉",     emoji: "🧵", level: 3, category: "hobby" },
  { word: "cycling",     translation: "騎單車",   emoji: "🚵", level: 3, category: "hobby" },

  // ==================== LEVEL 4：家具 (25) + 家電 (25) ====================
  // 家具 (25)
  { word: "sofa",        translation: "沙發",     emoji: "🛋️", level: 4, category: "furniture" },
  { word: "couch",       translation: "長沙發",   emoji: "🛋️", level: 4, category: "furniture" },
  { word: "desk",        translation: "書桌",     emoji: null, level: 4, category: "furniture" },
  { word: "shelf",       translation: "書架",     emoji: null, level: 4, category: "furniture" },
  { word: "drawer",      translation: "抽屜",     emoji: null, level: 4, category: "furniture" },
  { word: "wardrobe",    translation: "衣櫃",     emoji: null, level: 4, category: "furniture" },
  { word: "curtain",     translation: "窗簾",     emoji: null, level: 4, category: "furniture" },
  { word: "carpet",      translation: "地毯",     emoji: null, level: 4, category: "furniture" },
  { word: "wall",        translation: "牆壁",     emoji: null, level: 4, category: "furniture" },
  { word: "ceiling",     translation: "天花板",   emoji: null, level: 4, category: "furniture" },
  { word: "floor",       translation: "地板",     emoji: null, level: 4, category: "furniture" },
  { word: "pillow",      translation: "枕頭",     emoji: null, level: 4, category: "furniture" },
  { word: "blanket",     translation: "毯子",     emoji: null, level: 4, category: "furniture" },
  { word: "towel",       translation: "毛巾",     emoji: null, level: 4, category: "furniture" },
  { word: "basin",       translation: "臉盆",     emoji: null, level: 4, category: "furniture" },
  { word: "bathtub",     translation: "浴缸",     emoji: "🛁", level: 4, category: "furniture" },
  { word: "toilet",      translation: "馬桶",     emoji: "🚽", level: 4, category: "furniture" },
  { word: "sink",        translation: "水槽",     emoji: null, level: 4, category: "furniture" },
  { word: "bookcase",    translation: "書櫃",     emoji: null, level: 4, category: "furniture" },
  { word: "stool",       translation: "凳子",     emoji: null, level: 4, category: "furniture" },
  { word: "armchair",    translation: "扶手椅",   emoji: null, level: 4, category: "furniture" },
  { word: "bunk bed",    translation: "雙層床",   emoji: "🛏️", level: 4, category: "furniture" },
  { word: "rug",         translation: "小地毯",   emoji: null, level: 4, category: "furniture" },
  { word: "coat rack",   translation: "衣帽架",   emoji: null, level: 4, category: "furniture" },
  { word: "picture frame",translation: "相框",    emoji: "🖼️", level: 4, category: "furniture" },
  // 家電 (25)
  { word: "fridge",      translation: "冰箱",     emoji: "🧊", level: 4, category: "appliance" },
  { word: "washing machine",translation: "洗衣機",emoji: null, level: 4, category: "appliance" },
  { word: "microwave",   translation: "微波爐",   emoji: null, level: 4, category: "appliance" },
  { word: "oven",        translation: "烤箱",     emoji: null, level: 4, category: "appliance" },
  { word: "stove",       translation: "瓦斯爐",   emoji: "🔥", level: 4, category: "appliance" },
  { word: "fan",         translation: "電風扇",   emoji: "💨", level: 4, category: "appliance" },
  { word: "air conditioner",translation: "冷氣機",emoji: "❄️", level: 4, category: "appliance" },
  { word: "heater",      translation: "暖氣機",   emoji: "🌡️", level: 4, category: "appliance" },
  { word: "television",  translation: "電視",     emoji: "📺", level: 4, category: "appliance" },
  { word: "vacuum",      translation: "吸塵器",   emoji: null, level: 4, category: "appliance" },
  { word: "iron",        translation: "熨斗",     emoji: null, level: 4, category: "appliance" },
  { word: "blender",     translation: "果汁機",   emoji: null, level: 4, category: "appliance" },
  { word: "toaster",     translation: "烤麵包機", emoji: "🍞", level: 4, category: "appliance" },
  { word: "kettle",      translation: "電茶壺",   emoji: "🫖", level: 4, category: "appliance" },
  { word: "camera",      translation: "相機",     emoji: "📷", level: 4, category: "appliance" },
  { word: "radio",       translation: "收音機",   emoji: "📻", level: 4, category: "appliance" },
  { word: "calculator",  translation: "計算機",   emoji: null, level: 4, category: "appliance" },
  { word: "remote control",translation: "遙控器", emoji: null, level: 4, category: "appliance" },
  { word: "battery",     translation: "電池",     emoji: "🔋", level: 4, category: "appliance" },
  { word: "switch",      translation: "電源開關", emoji: null, level: 4, category: "appliance" },
  { word: "socket",      translation: "插座",     emoji: "🔌", level: 4, category: "appliance" },
  { word: "hair dryer",  translation: "吹風機",   emoji: null, level: 4, category: "appliance" },
  { word: "dishwasher",  translation: "洗碗機",   emoji: null, level: 4, category: "appliance" },
  { word: "rice cooker", translation: "電鍋",     emoji: null, level: 4, category: "appliance" },
  { word: "air purifier",translation: "空氣清淨機",emoji: null, level: 4, category: "appliance" },

  // ==================== LEVEL 5：職業 (25) + 社區場所 (25) ====================
  // 職業 (25)
  { word: "nurse",       translation: "護士",     emoji: "👩‍⚕️", level: 5, category: "job" },
  { word: "chef",        translation: "廚師",     emoji: "👨‍🍳", level: 5, category: "job" },
  { word: "baker",       translation: "麵包師",   emoji: "🥐", level: 5, category: "job" },
  { word: "farmer",      translation: "農夫",     emoji: "👨‍🌾", level: 5, category: "job" },
  { word: "fisherman",   translation: "漁夫",     emoji: "🎣", level: 5, category: "job" },
  { word: "soldier",     translation: "士兵",     emoji: "💂", level: 5, category: "job" },
  { word: "police",      translation: "警察",     emoji: "👮", level: 5, category: "job" },
  { word: "firefighter", translation: "消防員",   emoji: "👨‍🚒", level: 5, category: "job" },
  { word: "pilot",       translation: "飛行員",   emoji: "👨‍✈️", level: 5, category: "job" },
  { word: "driver",      translation: "司機",     emoji: "🚗", level: 5, category: "job" },
  { word: "engineer",    translation: "工程師",   emoji: "👷", level: 5, category: "job" },
  { word: "scientist",   translation: "科學家",   emoji: "🔬", level: 5, category: "job" },
  { word: "artist",      translation: "藝術家",   emoji: "🎨", level: 5, category: "job" },
  { word: "musician",    translation: "音樂家",   emoji: "🎵", level: 5, category: "job" },
  { word: "dancer",      translation: "舞者",     emoji: "💃", level: 5, category: "job" },
  { word: "actor",       translation: "演員",     emoji: "🎭", level: 5, category: "job" },
  { word: "writer",      translation: "作家",     emoji: "✍️", level: 5, category: "job" },
  { word: "lawyer",      translation: "律師",     emoji: "⚖️", level: 5, category: "job" },
  { word: "judge",       translation: "法官",     emoji: "👨‍⚖️", level: 5, category: "job" },
  { word: "dentist",     translation: "牙醫",     emoji: "🦷", level: 5, category: "job" },
  { word: "pharmacist",  translation: "藥劑師",   emoji: "💊", level: 5, category: "job" },
  { word: "vet",         translation: "獸醫",     emoji: "🐾", level: 5, category: "job" },
  { word: "reporter",    translation: "記者",     emoji: "📰", level: 5, category: "job" },
  { word: "astronaut",   translation: "太空人",   emoji: "👨‍🚀", level: 5, category: "job" },
  { word: "cook",        translation: "廚工",     emoji: "🍽️", level: 5, category: "job" },
  // 社區場所 (25)
  { word: "mall",        translation: "購物中心", emoji: "🏬", level: 5, category: "community" },
  { word: "police station",translation: "警察局", emoji: "🚓", level: 5, category: "community" },
  { word: "fire station",translation: "消防局",   emoji: "🚒", level: 5, category: "community" },
  { word: "train station",translation: "火車站",  emoji: "🚉", level: 5, category: "community" },
  { word: "bus stop",    translation: "公車站",   emoji: "🚌", level: 5, category: "community" },
  { word: "playground",  translation: "遊樂場",   emoji: "🛝", level: 5, category: "community" },
  { word: "museum",      translation: "博物館",   emoji: "🏛️", level: 5, category: "community" },
  { word: "cinema",      translation: "電影院",   emoji: "🎬", level: 5, category: "community" },
  { word: "theater",     translation: "劇場",     emoji: "🎭", level: 5, category: "community" },
  { word: "cafe",        translation: "咖啡廳",   emoji: "☕", level: 5, category: "community" },
  { word: "gym",         translation: "體育館",   emoji: "🏋️", level: 5, category: "community" },
  { word: "temple",      translation: "廟宇",     emoji: "⛩️", level: 5, category: "community" },
  { word: "supermarket", translation: "超市",     emoji: "🛒", level: 5, category: "community" },
  { word: "bookstore",   translation: "書店",     emoji: "📚", level: 5, category: "community" },
  { word: "bakery",      translation: "麵包店",   emoji: "🥖", level: 5, category: "community" },
  { word: "pharmacy",    translation: "藥局",     emoji: "💊", level: 5, category: "community" },
  { word: "gas station", translation: "加油站",   emoji: "⛽", level: 5, category: "community" },
  { word: "car wash",    translation: "洗車場",   emoji: "🚿", level: 5, category: "community" },
  { word: "laundry",     translation: "洗衣店",   emoji: null, level: 5, category: "community" },
  { word: "barber shop", translation: "理髮店",   emoji: "💈", level: 5, category: "community" },
  { word: "pet shop",    translation: "寵物店",   emoji: "🐾", level: 5, category: "community" },
  { word: "stadium",     translation: "體育場",   emoji: "🏟️", level: 5, category: "community" },
  { word: "community center",translation: "社區中心",emoji: "🏘️", level: 5, category: "community" },
  { word: "swimming pool",translation: "游泳池",  emoji: "🏊", level: 5, category: "community" },
  { word: "hotel",       translation: "飯店",     emoji: "🏨", level: 5, category: "community" },

  // ==================== LEVEL 6：海洋動物 (25) + 農場動物 (25) ====================
  // 海洋動物 (25)
  { word: "shark",       translation: "鯊魚",     emoji: "🦈", level: 6, category: "sea_animal" },
  { word: "dolphin",     translation: "海豚",     emoji: "🐬", level: 6, category: "sea_animal" },
  { word: "octopus",     translation: "章魚",     emoji: "🐙", level: 6, category: "sea_animal" },
  { word: "jellyfish",   translation: "水母",     emoji: "🪼", level: 6, category: "sea_animal" },
  { word: "lobster",     translation: "龍蝦",     emoji: "🦞", level: 6, category: "sea_animal" },
  { word: "shrimp",      translation: "蝦子",     emoji: "🦐", level: 6, category: "sea_animal" },
  { word: "starfish",    translation: "海星",     emoji: "⭐", level: 6, category: "sea_animal" },
  { word: "seahorse",    translation: "海馬",     emoji: null, level: 6, category: "sea_animal" },
  { word: "clam",        translation: "蛤蜊",     emoji: null, level: 6, category: "sea_animal" },
  { word: "oyster",      translation: "牡蠣",     emoji: null, level: 6, category: "sea_animal" },
  { word: "squid",       translation: "魷魚",     emoji: "🦑", level: 6, category: "sea_animal" },
  { word: "tuna",        translation: "鮪魚",     emoji: "🐟", level: 6, category: "sea_animal" },
  { word: "salmon",      translation: "鮭魚",     emoji: "🐟", level: 6, category: "sea_animal" },
  { word: "goldfish",    translation: "金魚",     emoji: "🐠", level: 6, category: "sea_animal" },
  { word: "seal",        translation: "海豹",     emoji: "🦭", level: 6, category: "sea_animal" },
  { word: "walrus",      translation: "海象",     emoji: null, level: 6, category: "sea_animal" },
  { word: "coral",       translation: "珊瑚",     emoji: "🪸", level: 6, category: "sea_animal" },
  { word: "seaweed",     translation: "海藻",     emoji: null, level: 6, category: "sea_animal" },
  { word: "anchovy",     translation: "鯷魚",     emoji: null, level: 6, category: "sea_animal" },
  { word: "swordfish",   translation: "旗魚",     emoji: "🐟", level: 6, category: "sea_animal" },
  { word: "clownfish",   translation: "小丑魚",   emoji: "🐠", level: 6, category: "sea_animal" },
  { word: "manta ray",   translation: "魟魚",     emoji: null, level: 6, category: "sea_animal" },
  { word: "sea turtle",  translation: "海龜",     emoji: "🐢", level: 6, category: "sea_animal" },
  { word: "narwhal",     translation: "獨角鯨",   emoji: "🐳", level: 6, category: "sea_animal" },
  { word: "manatee",     translation: "海牛",     emoji: null, level: 6, category: "sea_animal" },
  // 農場動物 (25)
  { word: "goat",        translation: "山羊",     emoji: "🐐", level: 6, category: "farm_animal" },
  { word: "donkey",      translation: "驢子",     emoji: "🫏", level: 6, category: "farm_animal" },
  { word: "goose",       translation: "鵝",       emoji: "🪿", level: 6, category: "farm_animal" },
  { word: "turkey",      translation: "火雞",     emoji: "🦃", level: 6, category: "farm_animal" },
  { word: "hamster",     translation: "倉鼠",     emoji: "🐹", level: 6, category: "farm_animal" },
  { word: "guinea pig",  translation: "天竺鼠",   emoji: null, level: 6, category: "farm_animal" },
  { word: "rooster",     translation: "公雞",     emoji: "🐓", level: 6, category: "farm_animal" },
  { word: "hen",         translation: "母雞",     emoji: "🐔", level: 6, category: "farm_animal" },
  { word: "lamb",        translation: "小羊",     emoji: "🐑", level: 6, category: "farm_animal" },
  { word: "calf",        translation: "小牛",     emoji: "🐮", level: 6, category: "farm_animal" },
  { word: "foal",        translation: "小馬",     emoji: "🐴", level: 6, category: "farm_animal" },
  { word: "kitten",      translation: "小貓",     emoji: "🐱", level: 6, category: "farm_animal" },
  { word: "puppy",       translation: "小狗",     emoji: "🐶", level: 6, category: "farm_animal" },
  { word: "chick",       translation: "小雞",     emoji: "🐥", level: 6, category: "farm_animal" },
  { word: "colt",        translation: "小公馬",   emoji: "🐴", level: 6, category: "farm_animal" },
  { word: "piglet",      translation: "小豬",     emoji: "🐷", level: 6, category: "farm_animal" },
  { word: "duckling",    translation: "小鴨",     emoji: "🐥", level: 6, category: "farm_animal" },
  { word: "gosling",     translation: "小鵝",     emoji: "🪿", level: 6, category: "farm_animal" },
  { word: "fawn",        translation: "小鹿",     emoji: "🦌", level: 6, category: "farm_animal" },
  { word: "mule",        translation: "騾子",     emoji: null, level: 6, category: "farm_animal" },
  { word: "ox",          translation: "公牛",     emoji: "🐂", level: 6, category: "farm_animal" },
  { word: "alpaca",      translation: "草泥馬",   emoji: "🦙", level: 6, category: "farm_animal" },
  { word: "peacock",     translation: "孔雀",     emoji: "🦚", level: 6, category: "farm_animal" },
  { word: "buffalo",     translation: "水牛",     emoji: "🐃", level: 6, category: "farm_animal" },
  { word: "ferret",      translation: "雪貂",     emoji: null, level: 6, category: "farm_animal" },

  // ==================== LEVEL 7：更多動詞 (30) + 副詞 (20) ====================
  // 更多動詞 (30)
  { word: "wake",        translation: "醒來",     emoji: "⏰", level: 7, category: "verb" },
  { word: "wash",        translation: "洗",       emoji: "🧼", level: 7, category: "verb" },
  { word: "brush",       translation: "刷",       emoji: "🪥", level: 7, category: "verb" },
  { word: "comb",        translation: "梳",       emoji: "💆", level: 7, category: "verb" },
  { word: "dress",       translation: "穿衣",     emoji: "👕", level: 7, category: "verb" },
  { word: "carry",       translation: "攜帶",     emoji: "🎒", level: 7, category: "verb" },
  { word: "lift",        translation: "舉起",     emoji: "💪", level: 7, category: "verb" },
  { word: "hit",         translation: "打",       emoji: "👊", level: 7, category: "verb" },
  { word: "count",       translation: "數",       emoji: "🔢", level: 7, category: "verb" },
  { word: "build",       translation: "建造",     emoji: "🏗️", level: 7, category: "verb" },
  { word: "break",       translation: "打破",     emoji: "💥", level: 7, category: "verb" },
  { word: "fix",         translation: "修理",     emoji: "🔧", level: 7, category: "verb" },
  { word: "fill",        translation: "填滿",     emoji: null, level: 7, category: "verb" },
  { word: "drop",        translation: "掉落",     emoji: null, level: 7, category: "verb" },
  { word: "pick",        translation: "撿",       emoji: null, level: 7, category: "verb" },
  { word: "wait",        translation: "等待",     emoji: "⏳", level: 7, category: "verb" },
  { word: "find",        translation: "找到",     emoji: "🔍", level: 7, category: "verb" },
  { word: "show",        translation: "展示",     emoji: null, level: 7, category: "verb" },
  { word: "share",       translation: "分享",     emoji: "🤝", level: 7, category: "verb" },
  { word: "choose",      translation: "選擇",     emoji: null, level: 7, category: "verb" },
  { word: "ask",         translation: "問",       emoji: "❓", level: 7, category: "verb" },
  { word: "answer",      translation: "回答",     emoji: "✅", level: 7, category: "verb" },
  { word: "think",       translation: "思考",     emoji: "💭", level: 7, category: "verb" },
  { word: "remember",    translation: "記得",     emoji: null, level: 7, category: "verb" },
  { word: "forget",      translation: "忘記",     emoji: null, level: 7, category: "verb" },
  { word: "know",        translation: "知道",     emoji: "💡", level: 7, category: "verb" },
  { word: "want",        translation: "想要",     emoji: "❤️", level: 7, category: "verb" },
  { word: "need",        translation: "需要",     emoji: null, level: 7, category: "verb" },
  { word: "love",        translation: "愛",       emoji: "❤️", level: 7, category: "verb" },
  { word: "hate",        translation: "討厭",     emoji: "💔", level: 7, category: "verb" },
  // 副詞 (20)
  { word: "quickly",     translation: "快速地",   emoji: "⚡", level: 7, category: "adverb" },
  { word: "slowly",      translation: "緩慢地",   emoji: "🐢", level: 7, category: "adverb" },
  { word: "loudly",      translation: "大聲地",   emoji: "📢", level: 7, category: "adverb" },
  { word: "quietly",     translation: "安靜地",   emoji: "🤫", level: 7, category: "adverb" },
  { word: "carefully",   translation: "小心地",   emoji: "⚠️", level: 7, category: "adverb" },
  { word: "happily",     translation: "快樂地",   emoji: "😊", level: 7, category: "adverb" },
  { word: "sadly",       translation: "難過地",   emoji: "😢", level: 7, category: "adverb" },
  { word: "angrily",     translation: "憤怒地",   emoji: "😠", level: 7, category: "adverb" },
  { word: "gently",      translation: "輕柔地",   emoji: null, level: 7, category: "adverb" },
  { word: "easily",      translation: "輕易地",   emoji: null, level: 7, category: "adverb" },
  { word: "suddenly",    translation: "突然地",   emoji: "💥", level: 7, category: "adverb" },
  { word: "always",      translation: "總是",     emoji: null, level: 7, category: "adverb" },
  { word: "never",       translation: "從不",     emoji: "🚫", level: 7, category: "adverb" },
  { word: "often",       translation: "經常",     emoji: null, level: 7, category: "adverb" },
  { word: "sometimes",   translation: "有時候",   emoji: null, level: 7, category: "adverb" },
  { word: "already",     translation: "已經",     emoji: "✅", level: 7, category: "adverb" },
  { word: "still",       translation: "仍然",     emoji: null, level: 7, category: "adverb" },
  { word: "soon",        translation: "不久",     emoji: "⏱️", level: 7, category: "adverb" },
  { word: "really",      translation: "真的",     emoji: "💯", level: 7, category: "adverb" },
  { word: "very",        translation: "非常",     emoji: null, level: 7, category: "adverb" },

  // ==================== LEVEL 8：情緒 (25) + 個性特質 (25) ====================
  // 情緒 (25)
  { word: "angry",       translation: "憤怒的",   emoji: "😠", level: 8, category: "emotion" },
  { word: "scared",      translation: "害怕的",   emoji: "😱", level: 8, category: "emotion" },
  { word: "jealous",     translation: "嫉妒的",   emoji: "😒", level: 8, category: "emotion" },
  { word: "worried",     translation: "擔心的",   emoji: "😟", level: 8, category: "emotion" },
  { word: "ashamed",     translation: "羞恥的",   emoji: "😳", level: 8, category: "emotion" },
  { word: "uncomfortable",translation: "不舒服的",emoji: "😖", level: 8, category: "emotion" },
  { word: "frustrated",  translation: "沮喪的",   emoji: "😤", level: 8, category: "emotion" },
  { word: "relaxed",     translation: "放鬆的",   emoji: "😌", level: 8, category: "emotion" },
  { word: "stressed",    translation: "有壓力的", emoji: "😰", level: 8, category: "emotion" },
  { word: "hopeful",     translation: "充滿希望的",emoji: "🌟", level: 8, category: "emotion" },
  { word: "disappointed",translation: "失望的",   emoji: "😞", level: 8, category: "emotion" },
  { word: "disgusted",   translation: "厭惡的",   emoji: "🤢", level: 8, category: "emotion" },
  { word: "amazed",      translation: "驚嘆的",   emoji: "😲", level: 8, category: "emotion" },
  { word: "calm",        translation: "平靜的",   emoji: "😐", level: 8, category: "emotion" },
  { word: "cheerful",    translation: "愉快的",   emoji: "😄", level: 8, category: "emotion" },
  { word: "miserable",   translation: "悲慘的",   emoji: "😫", level: 8, category: "emotion" },
  { word: "embarrassed", translation: "尷尬的",   emoji: "😅", level: 8, category: "emotion" },
  { word: "thrilled",    translation: "興高采烈的",emoji: "🤩", level: 8, category: "emotion" },
  { word: "heartbroken", translation: "心碎的",   emoji: "💔", level: 8, category: "emotion" },
  { word: "jealous",     translation: "羨慕的",   emoji: "😍", level: 8, category: "emotion" },
  { word: "envious",     translation: "眼紅的",   emoji: "🟢", level: 8, category: "emotion" },
  { word: "delighted",   translation: "高興的",   emoji: "😁", level: 8, category: "emotion" },
  { word: "grumpy",      translation: "脾氣壞的", emoji: "😾", level: 8, category: "emotion" },
  { word: "gloomy",      translation: "憂鬱的",   emoji: "😔", level: 8, category: "emotion" },
  { word: "content",     translation: "滿足的",   emoji: "😊", level: 8, category: "emotion" },
  // 個性特質 (25)
  { word: "brave",       translation: "勇敢的",   emoji: "🦁", level: 8, category: "trait" },
  { word: "kind",        translation: "善良的",   emoji: "💗", level: 8, category: "trait" },
  { word: "smart",       translation: "聰明的",   emoji: "🧠", level: 8, category: "trait" },
  { word: "funny",       translation: "有趣的",   emoji: "😂", level: 8, category: "trait" },
  { word: "lazy",        translation: "懶惰的",   emoji: "😴", level: 8, category: "trait" },
  { word: "hardworking", translation: "勤勞的",   emoji: "💪", level: 8, category: "trait" },
  { word: "honest",      translation: "誠實的",   emoji: "🙏", level: 8, category: "trait" },
  { word: "shy",         translation: "害羞的",   emoji: "😳", level: 8, category: "trait" },
  { word: "friendly",    translation: "友善的",   emoji: "🤝", level: 8, category: "trait" },
  { word: "polite",      translation: "有禮貌的", emoji: "🎩", level: 8, category: "trait" },
  { word: "rude",        translation: "無禮的",   emoji: "😤", level: 8, category: "trait" },
  { word: "gentle",      translation: "溫柔的",   emoji: "🌸", level: 8, category: "trait" },
  { word: "patient",     translation: "有耐心的", emoji: "⌛", level: 8, category: "trait" },
  { word: "creative",    translation: "有創意的", emoji: "🎨", level: 8, category: "trait" },
  { word: "curious",     translation: "好奇的",   emoji: "🔍", level: 8, category: "trait" },
  { word: "confident",   translation: "自信的",   emoji: "😎", level: 8, category: "trait" },
  { word: "stubborn",    translation: "固執的",   emoji: "🐂", level: 8, category: "trait" },
  { word: "generous",    translation: "大方的",   emoji: "🎁", level: 8, category: "trait" },
  { word: "selfish",     translation: "自私的",   emoji: null, level: 8, category: "trait" },
  { word: "careful",     translation: "謹慎的",   emoji: "⚠️", level: 8, category: "trait" },
  { word: "serious",     translation: "認真的",   emoji: "🧐", level: 8, category: "trait" },
  { word: "playful",     translation: "愛玩的",   emoji: "🎈", level: 8, category: "trait" },
  { word: "talented",    translation: "有才華的", emoji: "🌟", level: 8, category: "trait" },
  { word: "responsible", translation: "負責任的", emoji: null, level: 8, category: "trait" },
  { word: "independent", translation: "獨立的",   emoji: null, level: 8, category: "trait" },

  // ==================== LEVEL 9：地理 (20) + 太空/天空 (15) + 自然現象 (15) ====================
  // 地理 (20)
  { word: "valley",      translation: "山谷",     emoji: null, level: 9, category: "geography" },
  { word: "lake",        translation: "湖泊",     emoji: "🏞️", level: 9, category: "geography" },
  { word: "island",      translation: "島嶼",     emoji: "🏝️", level: 9, category: "geography" },
  { word: "plain",       translation: "平原",     emoji: null, level: 9, category: "geography" },
  { word: "hill",        translation: "山丘",     emoji: "⛰️", level: 9, category: "geography" },
  { word: "cave",        translation: "洞穴",     emoji: null, level: 9, category: "geography" },
  { word: "cliff",       translation: "懸崖",     emoji: null, level: 9, category: "geography" },
  { word: "waterfall",   translation: "瀑布",     emoji: "💧", level: 9, category: "geography" },
  { word: "coast",       translation: "海岸",     emoji: "🏖️", level: 9, category: "geography" },
  { word: "bay",         translation: "海灣",     emoji: null, level: 9, category: "geography" },
  { word: "peninsula",   translation: "半島",     emoji: null, level: 9, category: "geography" },
  { word: "glacier",     translation: "冰河",     emoji: "❄️", level: 9, category: "geography" },
  { word: "swamp",       translation: "沼澤",     emoji: null, level: 9, category: "geography" },
  { word: "canyon",      translation: "峽谷",     emoji: null, level: 9, category: "geography" },
  { word: "plateau",     translation: "高原",     emoji: null, level: 9, category: "geography" },
  { word: "grassland",   translation: "草原",     emoji: "🌾", level: 9, category: "geography" },
  { word: "tundra",      translation: "凍原",     emoji: null, level: 9, category: "geography" },
  { word: "savanna",     translation: "莽原",     emoji: "🌿", level: 9, category: "geography" },
  { word: "rainforest",  translation: "雨林",     emoji: "🌴", level: 9, category: "geography" },
  { word: "wetland",     translation: "濕地",     emoji: null, level: 9, category: "geography" },
  // 太空/天空 (15)
  { word: "sun",         translation: "太陽",     emoji: "☀️", level: 9, category: "space" },
  { word: "moon",        translation: "月亮",     emoji: "🌙", level: 9, category: "space" },
  { word: "comet",       translation: "彗星",     emoji: "☄️", level: 9, category: "space" },
  { word: "meteor",      translation: "流星",     emoji: "🌠", level: 9, category: "space" },
  { word: "galaxy",      translation: "銀河",     emoji: "🌌", level: 9, category: "space" },
  { word: "satellite",   translation: "衛星",     emoji: "🛰️", level: 9, category: "space" },
  { word: "rocket",      translation: "火箭",     emoji: "🚀", level: 9, category: "space" },
  { word: "telescope",   translation: "望遠鏡",   emoji: "🔭", level: 9, category: "space" },
  { word: "orbit",       translation: "軌道",     emoji: null, level: 9, category: "space" },
  { word: "nebula",      translation: "星雲",     emoji: "🌌", level: 9, category: "space" },
  { word: "asteroid",    translation: "小行星",   emoji: "☄️", level: 9, category: "space" },
  { word: "black hole",  translation: "黑洞",     emoji: "🌑", level: 9, category: "space" },
  { word: "constellation",translation: "星座",    emoji: "✨", level: 9, category: "space" },
  { word: "astronomer",  translation: "天文學家", emoji: "🔭", level: 9, category: "space" },
  { word: "gravity",     translation: "重力",     emoji: null, level: 9, category: "space" },
  // 自然現象 (15)
  { word: "hurricane",   translation: "颶風",     emoji: "🌀", level: 9, category: "nature" },
  { word: "flood",       translation: "洪水",     emoji: "🌊", level: 9, category: "nature" },
  { word: "drought",     translation: "乾旱",     emoji: "☀️", level: 9, category: "nature" },
  { word: "lightning",   translation: "閃電",     emoji: "⚡", level: 9, category: "nature" },
  { word: "fog",         translation: "霧",       emoji: "🌫️", level: 9, category: "nature" },
  { word: "frost",       translation: "霜",       emoji: "❄️", level: 9, category: "nature" },
  { word: "avalanche",   translation: "雪崩",     emoji: "🏔️", level: 9, category: "nature" },
  { word: "tide",        translation: "潮汐",     emoji: "🌊", level: 9, category: "nature" },
  { word: "wave",        translation: "海浪",     emoji: "🌊", level: 9, category: "nature" },
  { word: "storm",       translation: "暴風雨",   emoji: "⛈️", level: 9, category: "nature" },
  { word: "breeze",      translation: "微風",     emoji: "💨", level: 9, category: "nature" },
  { word: "hail",        translation: "冰雹",     emoji: "🌨️", level: 9, category: "nature" },
  { word: "blizzard",    translation: "暴風雪",   emoji: "❄️", level: 9, category: "nature" },
  { word: "landslide",   translation: "山崩",     emoji: null, level: 9, category: "nature" },
  { word: "eruption",    translation: "火山噴發", emoji: "🌋", level: 9, category: "nature" },

  // ==================== LEVEL 10：科技 (20) + 環境/自然 (15) + 健康/身體 (15) ====================
  // 科技 (20)
  { word: "internet",    translation: "網路",     emoji: "🌐", level: 10, category: "technology" },
  { word: "website",     translation: "網站",     emoji: "🌐", level: 10, category: "technology" },
  { word: "email",       translation: "電子郵件", emoji: "📧", level: 10, category: "technology" },
  { word: "password",    translation: "密碼",     emoji: "🔑", level: 10, category: "technology" },
  { word: "keyboard",    translation: "鍵盤",     emoji: "⌨️", level: 10, category: "technology" },
  { word: "mouse",       translation: "滑鼠",     emoji: "🖱️", level: 10, category: "technology" },
  { word: "screen",      translation: "螢幕",     emoji: "🖥️", level: 10, category: "technology" },
  { word: "charger",     translation: "充電器",   emoji: "🔌", level: 10, category: "technology" },
  { word: "cable",       translation: "電纜",     emoji: null, level: 10, category: "technology" },
  { word: "robot",       translation: "機器人",   emoji: "🤖", level: 10, category: "technology" },
  { word: "program",     translation: "程式",     emoji: "💻", level: 10, category: "technology" },
  { word: "code",        translation: "程式碼",   emoji: "👨‍💻", level: 10, category: "technology" },
  { word: "app",         translation: "應用程式", emoji: "📱", level: 10, category: "technology" },
  { word: "digital",     translation: "數位的",   emoji: null, level: 10, category: "technology" },
  { word: "download",    translation: "下載",     emoji: "⬇️", level: 10, category: "technology" },
  { word: "upload",      translation: "上傳",     emoji: "⬆️", level: 10, category: "technology" },
  { word: "virus",       translation: "病毒",     emoji: "🦠", level: 10, category: "technology" },
  { word: "network",     translation: "網絡",     emoji: "🔗", level: 10, category: "technology" },
  { word: "cloud",       translation: "雲端",     emoji: "☁️", level: 10, category: "technology" },
  { word: "bluetooth",   translation: "藍牙",     emoji: null, level: 10, category: "technology" },
  // 環境/自然 (15)
  { word: "recycle",     translation: "回收",     emoji: "♻️", level: 10, category: "environment" },
  { word: "carbon",      translation: "碳",       emoji: null, level: 10, category: "environment" },
  { word: "oxygen",      translation: "氧氣",     emoji: "💨", level: 10, category: "environment" },
  { word: "wildlife",    translation: "野生動物", emoji: "🦁", level: 10, category: "environment" },
  { word: "habitat",     translation: "棲息地",   emoji: "🌿", level: 10, category: "environment" },
  { word: "extinct",     translation: "滅絕的",   emoji: "💀", level: 10, category: "environment" },
  { word: "protect",     translation: "保護",     emoji: "🛡️", level: 10, category: "environment" },
  { word: "climate",     translation: "氣候",     emoji: "🌍", level: 10, category: "environment" },
  { word: "greenhouse",  translation: "溫室",     emoji: "🌿", level: 10, category: "environment" },
  { word: "solar",       translation: "太陽能的", emoji: "☀️", level: 10, category: "environment" },
  { word: "wind power",  translation: "風力",     emoji: "💨", level: 10, category: "environment" },
  { word: "ecosystem",   translation: "生態系統", emoji: "🌱", level: 10, category: "environment" },
  { word: "deforestation",translation: "砍伐森林",emoji: "🌲", level: 10, category: "environment" },
  { word: "conservation",translation: "自然保育", emoji: "🐾", level: 10, category: "environment" },
  { word: "biodiversity",translation: "生物多樣性",emoji: "🌿", level: 10, category: "environment" },
  // 健康/身體 (15)
  { word: "vitamin",     translation: "維生素",   emoji: "💊", level: 10, category: "health" },
  { word: "protein",     translation: "蛋白質",   emoji: "🥩", level: 10, category: "health" },
  { word: "exercise",    translation: "運動",     emoji: "🏃", level: 10, category: "health" },
  { word: "breathe",     translation: "呼吸",     emoji: "💨", level: 10, category: "health" },
  { word: "heartbeat",   translation: "心跳",     emoji: "❤️", level: 10, category: "health" },
  { word: "muscle",      translation: "肌肉",     emoji: "💪", level: 10, category: "health" },
  { word: "bone",        translation: "骨頭",     emoji: "🦴", level: 10, category: "health" },
  { word: "skin",        translation: "皮膚",     emoji: null, level: 10, category: "health" },
  { word: "blood",       translation: "血液",     emoji: "🩸", level: 10, category: "health" },
  { word: "brain",       translation: "大腦",     emoji: "🧠", level: 10, category: "health" },
  { word: "lung",        translation: "肺",       emoji: null, level: 10, category: "health" },
  { word: "medicine",    translation: "藥",       emoji: "💊", level: 10, category: "health" },
  { word: "disease",     translation: "疾病",     emoji: "🤒", level: 10, category: "health" },
  { word: "vaccine",     translation: "疫苗",     emoji: "💉", level: 10, category: "health" },
  { word: "nutrition",   translation: "營養",     emoji: "🥗", level: 10, category: "health" },

];
